version: '1.0'

volumes:
  logs: {}
  postgres_data: {}

services:
  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password


  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - '5435:5435'
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
    command: -p 5435

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
