basePath: /
definitions:
  app.User:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: API Server for Avito Dynamic Segment Application
  title: Avito Dynamic Segment App API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: create user
      operationId: create-user
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create user
      tags:
      - users
swagger: "2.0"
